### ISSUE TITLE
Removal of "linux-4.4-rockpis-latest" from repo broke "rockpis-rk-ubootimg" install

### ISSUE THREAD

**Issue by MichaIng** [radxa/apt#10]
`rockpis-rk-u-boot-latest` depends on `rockpis-rk-ubootimg`, which depends on `linux-4.4-rockpis-latest`. But the latter has been removed from the repository in favour of `linux-4.4-rock-pi-s-latest`: https://github.com/radxa/apt/commit/f0bedc4793c611aa244def5dd3cf833c3c325305

So practically the bootloader cannot be installed/upgraded with this change and I guess it has been forgotten to adjust the kernel package name in the `rockpis-rk-ubootimg` dependencies.

In case of `rockpie-rk-ubootimg` (ROCK Pi E), there is no dependency on the kernel package at all, which means the issue only affects the ROCK Pi S.

**Comment by StephenInVamrs** [comment]
This issue is fixed.

Get the new public key like this
```
wget -O - apt.radxa.com/buster-stable/public.key | sudo apt-key add -
```
And execute the following command.
```
sudo apt-get update
```

**Comment by MichaIng** [comment]
Great, many thanks for resolving this quickly 👍.
