### ISSUE TITLE
Can't find package rockchip-mali-midgard-dev on Ubuntu 20.04

### ISSUE THREAD

**Issue by MisakaMikoto-35c5** [radxa/apt#14]
I'm following [this guide](https://wiki.radxa.com/Rockpi4/dev/install-opencl) to install OpenCL drivers, but apt can't find `rockchip-mali-midgard14` and `rockchip-mali-midgard-dev` on focal-testing repo.

**Comment by ghost-458** [comment]
Can confirm this package is missing from 20.04.

**Comment by StephenInVamrs** [comment]
They are added. You can check this commit https://github.com/radxa/apt/commit/24f9636e9e3ee83f39046a956c403fb623c7f617
