### ISSUE TITLE
rockchip-overlay package conflicts with firmware-misc-nonfree

### ISSUE THREAD

**Issue by MichaIng** [radxa/apt#15]
The new [rockchip-overlay v2.9](https://github.com/radxa/apt/tree/gh-pages/buster-stable/pool/main/r/rockchip-overlay) contains `/lib/firmware/rockchip/dptx.bin`, which is also contained in Debian's [firmware-misc-nonfree](https://packages.debian.org/buster/all/firmware-misc-nonfree/filelist), which is pretty commonly installed to provide firmware for a lot of devices, like Ethernet, WiFi and Bluetooth chips, audio DACs and similar.

I'm not sure whether this particular firmware from the Radxa package is somehow better, and how to resolve best. It could be placed into a different directory, theoretically `/usr/local/lib/firmware`, or the package could contain some conflict/replaces/provides attributes, though I'm currently not sure how well this works to allow an overlap of only a single file. But currently users run into APT upgrade failures and many don't know how to resolve it.

**Comment by StephenInVamrs** [comment]
Hi @MichaIng . dptx.bin is used for RK3399 ROCK Pi 4C DP driver, which specifies the location, /lib/firmware/rockchip/dptx.bin.

**Comment by MichaIng** [comment]
Okay, if the path cannot be changed, then the package marks need to either define a conflict or allow the file overlap. An alternative to would be to not ship this firmware with your package on Debian but instead have the generic Debian firmware package installed. But I guess this makes it complicated when using the same package on Ubuntu, where this generic firmware package does not exist 🤔.

I checked the docs: https://www.debian.org/doc/manuals/debian-faq/pkg-basics.en.html#depends
Adding
```
Replaces: firmware-misc-nonfree
```
to the `rockchip-overlay` package control file would allow it to be installed concurrently, replacing files of `firmware-misc-nonfree`.

**Comment by StephenInVamrs** [comment]
File dptx.bin is removed in the latest rockchip-overlay package.

I think there is no conflicts between rockchip-overlay and firmware-misc-nonfree.

**Comment by MichaIng** [comment]
Many thanks, I can confirm that the issue is solved in the testing repositories. Hoping for a soon update on stable repositories 🙂.
