### ISSUE TITLE
libmraa broken dependency libjson-c3 in Ubuntu focal 20.04

### ISSUE THREAD

**Issue by myroad94** [radxa/apt#18]
Hi,

Hardware:
Rock Pi 4C with Penta HAT

OS:
Ubuntu https://github.com/radxa/rock-pi-images-released/releases/download/v20210824/rockpi4c_ubuntu_focal_server_arm64_20210823_2200-gpt.img.gz

Current behavior:
When following https://wiki.radxa.com/Penta_SATA_HAT
`curl -sL https://rock.sh/get-rockpi-penta | sudo -E bash -`

It fails during the installation of libmraa
`E: Package 'libjson-c3' has no installation candidate`

Expected behavior:
Installation of get-rockpi-penta works.

Analysis:
The dependency libjson-c3 exist in Ubuntu Bionic but not in Focal anymore. It seems to me that it has been replaced by libjson-c4 in Focal (20.04). And libjson-c5 in Ubuntu Hirsuite (21.04).

Solution:
Replace in https://github.com/radxa/apt/blob/gh-pages/focal-stable/dists/focal/main/binary-arm64/Packages#L151 the dependency by libjson-c4.

**Comment by myroad94** [comment]
Workaround:
I remark that the fix is done at focal-testing https://github.com/radxa/apt/blob/gh-pages/focal-testing/dists/focal/main/binary-arm64/Packages#L201
So we can use focal-testing branch of apt radxa:
```
sudo sed -i -E "s,^deb(.*)focal-stable(.*),#deb\1focal-stable\2,g" /etc/apt/sources.list.d/apt-radxa-com.list
sudo sed -i -E "s,^#( *)deb(.*)focal-testing(.*),deb\2focal-testing\3,g" /etc/apt/sources.list.d/apt-radxa-com.list
```
Then the installation works.

**Comment by dev-radxa** [comment]
Package libmraa (v1.6) fixes this issue of broken dependency libjson-c3.
Now I close this issue.

**Comment by StephenInVamrs** [comment]
Package libmraa (v1.6) fixes this issue of broken dependency libjson-c3.
