### ISSUE TITLE
The signature for the Rasbian Jessie repository is not valid

### ISSUE THREAD

**Issue by c0va23** [radxa/apt#2]
Hey. After changing the repository link to https://apt.radxa.com/rabian-stable/, the command `sudo apt update` runs with this error:

```
rock@radxa:/etc/apt/sources.list.d$ curl https://apt.radxa.com/rabian-stable/public.key | sudo apt-key add -v -
rock@radxa:/etc/apt/sources.list.d$ sudo apt update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Get:4 http://apt.radxa.com/rabian-stable jessie InRelease [2087 B]                           
Err:4 http://apt.radxa.com/rabian-stable jessie InRelease                                               
  The following signatures were invalid: BADSIG C184E3BA32B4B98C build (radxa apt server) <build@radxa.com>
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease       
Hit:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release                   
Reading package lists... Done
W: GPG error: http://apt.radxa.com/rabian-stable jessie InRelease: The following signatures were invalid: BADSIG C184E3BA32B4B98C build (radxa apt server) <build@radxa.com>
E: The repository 'http://apt.radxa.com/rabian-stable jessie InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by hipboi** [comment]
Hi,

Which hardware and image are you using?

**Comment by c0va23** [comment]
I use Radxa Rock2 Square (2GB) with Rasbian (https://dl.radxa.com/rock2/images/rabian/emmc/rock2_square_rabian_150720_5d53487_emmc.img.xz)

**Comment by c0va23** [comment]
I see that the file "rabian-stable/dists/jessie/Release" was updated 2 months ago, but the file "rabian-stable/dists/jessie/Release.gpg" was updated three years ago. It may be that the signature forgot to update when you move the repository to a new domain "apt.radxa.com".

![image](https://user-images.githubusercontent.com/587257/50392193-4b687280-075d-11e9-8c87-39f1d9f3bbc2.png)

**Comment by StephenInVamrs** [comment]
Hi, c0va23

We have already update all the packages. 

You can update the public key by
    wget -O -  apt.radxa.com/rabian-stable/public.key | sudo apt-key add -

And then install your wanted packages.

**Comment by c0va23** [comment]
Now the update works! Thank you!
