### ISSUE TITLE
Enable nfsd kernel module (Ubuntu server)

### ISSUE THREAD

**Issue by AndersDala** [radxa/apt#3]
Hi,

Having NFS support in the kernel would be very appreciated if possible. :-)
In order to support it, at least the following module must be available:
kernel/fs/nfsd

Thanks in advance,
Anders

**Comment by StephenInVamrs** [comment]
Module nfsd is added and it works. I test it ａccording to this guide, https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nfs-mount-on-ubuntu-16-04. It works on ROCK Pi 4 Ubuntu server (kernel : >=4.4.154-81)

**Comment by AndersDala** [comment]
Confirmed, works for me as well, thanks a lot!
