### ISSUE TITLE
MPP and RGA are missing in Ubuntu focal

### ISSUE THREAD

**Issue by nyanmisaka** [radxa/apt#44]
Debian bullseye already has MPP and RGA libs. Please add them to Ubuntu focal.

https://github.com/radxa/apt/tree/gh-pages/bullseye-stable/pool/main/m/mpp
https://github.com/radxa/apt/tree/gh-pages/bullseye-stable/pool/main/libr/librga
https://github.com/radxa/apt/tree/gh-pages/bullseye-stable/pool/main/libv/libv4l-rkmpp

**Comment by RadxaYuntian** [comment]
Those packages are prebuilt by Rockchip for Debian system. We have tried to install them on Ubuntu Jammy, and there are missing dependencies that Jammy does not ship.

I understand you are asking for Focal, which might have different result regarding missing dependencies, but ultimately this is not a supported use case. The proper way for us to ship them is rebuilding and repackaging them for each Ubuntu release. The resulting binaries still miss testing from Rockchip end, and any possible issues are unlikely to be supported by them.

Currently we do not have the resource to support this use case alone, so they are unfortunately unavailable for Ubuntu images.

**Comment by nyanmisaka** [comment]
That make sense. Thanks anyway.
