### ISSUE TITLE
Libmraa armhf version for bullseye

### ISSUE THREAD

**Issue by shawaj** [radxa/apt#51]
Please can you build an armhf version of libmraa for Debian bullseye-stable?

**Comment by shawaj** [comment]
@RadxaStephen @hipboi @dev-radxa @StephenInVamRs

Can you help with this?

**Comment by RadxaStephen** [comment]
Sure. Please give me some time.

**Comment by shawaj** [comment]
Thanks very much @RadxaStephen that's great ☺️

**Comment by shawaj** [comment]
Any progress yet @RadxaStephen ?

**Comment by shawaj** [comment]
@RadxaStephen any update on this?

**Comment by RadxaYuntian** [comment]
@nascs is currently working on this.

**Comment by shawaj** [comment]
@nascs do you have a timeline when this will be ready?

**Comment by nascs** [comment]
Just tested, uart has some problems, and now I'm trying to fix it.

**Comment by shawaj** [comment]
Thanks @nascs 👍

**Comment by nascs** [comment]
I have compiled a bullseye armhf debian package, but we don't have a Debian 11 image of armhf, so the test have not be done, I wonder if you could test it for us ?

**Comment by RadxaStephen** [comment]
@nascs 

You can use [rockchip-bsp](https://github.com/radxa/rockchip-bsp) to build one debian11 armhf image.

**Comment by shawaj** [comment]
@nascs @RadxaStephen is it added to the apt repo already?

If it's added I can test it

**Comment by nascs** [comment]
@shawaj  file:///home/nasca/libmraa_1.9_armhf.zip  This deb package has not been tested yet,  and I will compile an image of debian11 armhf for testing tomorrow , you can test it too, and if any errors , please let me know, thanks for your testing help.

**Comment by nascs** [comment]
[libmraa_1.9_armhf.zip](https://github.com/radxa/apt/files/10392555/libmraa_1.9_armhf.zip)

**Comment by nascs** [comment]
This deb package has not been tested yet, and I will compile an image of debian11 armhf for testing tomorrow , you can test it too, and if any errors , please let me know, thanks for your testing help.

**Comment by shawaj** [comment]
@nascs can you add it to the bullseye-testing? This is best way for us to test it

**Comment by shawaj** [comment]
@nascs @RadxaStephen any update?

**Comment by nascs** [comment]
we will update  apt by this evening Beijing time.

**Comment by shawaj** [comment]
> we will update apt by this evening Beijing time.

🙌🙏

**Comment by shawaj** [comment]
@RadxaStephen @nascs it's not working properly.

It doesn't load / import into python...

![212917040-126083d1-b83a-4af0-a45e-3227ff229ad8](https://user-images.githubusercontent.com/3359418/212942168-6302a65f-4b26-4fc4-9f38-c921ff5183a0.png)

See the code here:
https://github.com/NebraLtd/hm-config/blob/master/gatewayconfig/gpio/mraa_gpio.py#L6-L10

Cc @KevinWassermann94

**Comment by shawaj** [comment]
I think it is because libmraa here - https://github.com/radxa/apt/blob/cac0e24f05a9982d3d67285822591ff117a26707/bullseye-stable/pool/main/libm/libmraa/libmraa_1.9_armhf.deb - is only built for python 2.7 and python 3.9. Not 3.11

**Comment by shawaj** [comment]
It also does not work with python3.9 the latest version. there is nothing installed in `/usr/local/lib/python3.9/dist-packages`

Not sure if this is also relevant:

```
Setting up libmraa (1.9) ...
sudo: unable to resolve host 6d181a5: No address associated with hostname
ldconfig: /lib/libmraa.so.2 is not a symbolic link

Processing triggers for mailcap (3.69) ...
Processing triggers for libc-bin (2.31-13+rpi1+deb11u3) ...
ldconfig: /lib/libmraa.so.2 is not a symbolic link
```

**Comment by shawaj** [comment]
@RadxaStephen @nascs it seems /lib/libmraa.so.2 and /lib/libmraa.so should be symbolic links of /lib/libmraa.so.2.1.0 rather than individual files

**Comment by shawaj** [comment]
@RadxaStephen @nascs I can confirm that if I pull the `mraa.py` and `_mraa.so` files out of the [deb package in the repo](https://github.com/radxa/apt/blob/gh-pages/bullseye-stable/pool/main/libm/libmraa/libmraa_1.9_armhf.deb) and put them in `/usr/local/lib/python3.9/dist-packages` it works correctly.

So it looks like the package is just built wrong.

- `libmraa.so.2` and `libmraa.so` should be symbolic links not files
- the deb package should automatically install the `mraa.py` and `_mraa.so` files into `/usr/local/lib/python3.9/dist-packages`
- you should add python3.11 as part of build

Can you sort this?

**Comment by RadxaYuntian** [comment]
I have checked that Debian bullseye ship Python 3.9 by default. How did you install Python 3.11 on your system?

Also, software packaged and shipped via apt repo is considered distro managed, and as such should not install to `/usr/local` path to not breaking Filesystem Hierarchy Standard.

**Comment by shawaj** [comment]
@RadxaYuntian by default Balena install the latest python version. So need it to support 3.9 and 3.11

Your current packages do not install correctly. Perhaps it is because of the previous point:

> libmraa.so.2 and libmraa.so should be symbolic links not files

Also on your buster-stable package it does install to `/usr/local/lib/python3.7/dist-packages`

**Comment by nascs** [comment]
It will be handled today.

**Comment by RadxaYuntian** [comment]
@floion How do you guys support custom python libraries in your system? Right now we are bending backwards to support a downstream usage, which feels very awkward since we don't even have any armhf images or build infrastructure.

I have asked nascs to be on hold until we know how Balena deals with this type of problems.

**Comment by shawaj** [comment]
@RadxaYuntian it is sufficient to just do the standard python 3.9 build as we can use venv for that.

But we still need the other parts fixing.

@nascs can you still sort this today?

It is very urgent now

**Comment by RadxaStephen** [comment]
@shawaj 

Debian11 armhf libmraa (2.0) is released. Python version is 2.7/3.9.

I test the following commands on ROCK Pi 4B Debian11 Armhf image. And they run without error.

```
mraa-gpio version
Version v2.1.0-25-gf854463 on ROCK Pi 4

mraa-gpio list
```


 Can you test it?

**Comment by RadxaStephen** [comment]
For your need of python3.11, you can built mraa on your device.

Please refer to this guide, https://wiki.radxa.com/Mraa. And see this part, "Install example: Install Mraa on ROCK Pi 4B Debian11 armhf system".

**Comment by shawaj** [comment]
@RadxaStephen thanks very much.

@KevinWassermann94 @NebraLtd/tech-support I've pushed this to testnet now. It looks like it is working to me but could you test was well to check it on your side?

**Comment by shawaj** [comment]
Cc @WayneNebra ^^

**Comment by KevinWassermann94** [comment]
@shawaj Looks fine to me!

**Comment by shawaj** [comment]
@RadxaStephen @RadxaYuntian @nascs thanks for your help, it's working now :-)
