### ISSUE TITLE
Where is the OpenCL driver for Mali

### ISSUE THREAD

**Issue by sueng66** [radxa/apt#7]
I couldn't found any openCL driver for Mali T860 it was rockchip-mali-midgard14 , now I couldn't found it

**Comment by akgnah** [comment]
Please refer to https://wiki.radxa.com/Rockpi4/dev/install-opencl

I tested it before I got back to you.

**Comment by StephenInVamrs** [comment]
@akgnah  have confirmed that OpenCL is supported for ROCK Pi 4.
