### ISSUE TITLE
Repository Key for Buster-Stable has expired

### ISSUE THREAD

**Issue by custodis-intestina** [radxa/apt#9]
The key to Buster Stable has expired as of today. No APT-GET update or upgrade possible

> Holen:1 http://apt.radxa.com/buster-stable buster InRelease [2.360 B]
OK:2 https://deb.debian.org/debian buster InRelease
OK:3 https://deb.debian.org/debian buster-updates InRelease
OK:4 https://deb.debian.org/debian-security buster/updates InRelease
OK:5 https://deb.debian.org/debian buster-backports InRelease
Fehl:1 http://apt.radxa.com/buster-stable buster InRelease
  Die folgenden Signaturen waren ungültig: EXPKEYSIG 5761288B2B52CC90 Radxa <dev@radxa.com>
Paketlisten werden gelesen... Fertig
W: GPG-Fehler: http://apt.radxa.com/buster-stable buster InRelease: Die folgenden Signaturen waren ungültig: EXPKEYSIG 5761288B2B52CC90 Radxa <dev@radxa.com>
E: Das Depot »http://apt.radxa.com/buster-stable buster InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

> pub   rsa3072 2018-11-23 [SC] [verfallen: 2020-11-22]

      C79E F8D1 49CF C9C0 418A  9A60 5761 288B 2B52 CC90
uid        [ verfallen ] Radxa <dev@radxa.com>

**Comment by MichaIng** [comment]
All suites affected, also the key from the repo here is the same, expired: https://github.com/radxa/apt/blob/gh-pages/buster-stable/public.key

**Comment by Sejwiur** [comment]
The same with Ubuntu bionic.

**Comment by nearxos** [comment]
having the same issue here

**Comment by StephenInVamrs** [comment]
We have fixed this already.
What we need to do is to get a new public key before updating the APT repository.

```
wget -O - apt.radxa.com/buster-stable/public.key | sudo apt-key add -
sudo apt-get update
```
